apiVersion: apps/v1
kind: Deployment
metadata:
   name: personalpodcast
spec:
   replicas: 2
   selector:
      matchLabels:
         app: personalpodcast
   template:
      metadata:
         labels:
            app: personalpodcast
      spec:
         containers:
            - name: personalpodcast
              image: erzengamerx/personalpodcast:latest
              ports:
                 - containerPort: 8080
